[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[forms]
  [forms.contact]
    [forms.contact.settings]
      to = "francisgcastellano1@gmail.com"
      subject = "Nuevo contacto desde Pucará Gaming"
